### ISSUE TITLE
A friendly hello :)

### ISSUE THREAD

**Issue by MeoMix** [ptgamr/soundcloudify#2]
Just stopping in to say I noticed your work! I see you borrowed a bit of the code from Streamus. Glad to see that you are open source and under the same licensing. Let me know if you have any questions or want to talk ideas.

**Comment by ptgamr** [comment]
Greetings from me :) Thanks for the work with Streamus. At first I just want to try to make something with Angular, but it turns out SoundCloudify. I borrow some logic of Streamus in the background page to communicate with Youtube, I guess you also had hard time with this before. So, thanks for that! If you have any idea, feel free to contact me :+1:
